### ISSUE TITLE
Rewrite needed

### ISSUE THREAD

**Issue by jhoak** [jhoak/RBFS#1]
Even though it basically works, the code quality and the features here are unsatisfactory -- need to overhaul the system at some point to implement complete concurrency, better UI, and better support for editing different file types. (Spring '16?) (And no, it wouldn't be better to reuse this code.)

**Comment by nanflasted** [comment]
K

**Comment by jhoak** [comment]
Rewrite in progress. Commits are happening.

**Comment by nanflasted** [comment]
Wow closed? is it done?

**Comment by jhoak** [comment]
> "Commits are happening."

It's in progress. More to be committed tonight and tomorrow. ETA Mon/Tues.

**Comment by nanflasted** [comment]
Nice Keep up!
